# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98bb31dd3587b48e94c56d3bcfd41319f539dbf5adae399a547ccfa9ecd26342ab62fc8036246ead847c802c28d7f9ca08a06ef8b38b0f4c44498d1d2f3bdd9a

test:
  secret_key_base: 36cb1412da3d7718232699d9174e4cba3918554fe6e0041b62a800211c622eb539a4209099a1e8e16957fad485ce0ea9154b1714bf51c126062d458d92e305e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
